### PR TITLE
Bump FlatBuffers version to 2.0.0

### LINKED ISSUE #2: Update flatc version to 2.0.0
Hi there. This crate looks great, and is exactly what I need to add building my flatbuffers schema to my build.rs script. The one snag I've run into is that my schema uses optional scalars, which are only supported from Flatc 2.0.0 (https://github.com/google/flatbuffers/releases/tag/v2.0.0).

### PR DESCRIPTION
**Pull request by JWorthe**
Release notes for FlatBuffers 2.0.0: https://github.com/google/flatbuffers/releases/tag/v2.0.0

Fixes #2

### CODE REVIEW

**Comment by JWorthe** [comment]
I've only tested this on Linux, but it works on my machine.

**Comment by chippers** [comment]
I'll look at this tonight or tomorrow and prepare a release

**Comment by JWorthe** [comment]
Hi @chippers! Did you get a chance to look at this yet?

**Comment by chippers** [comment]
> Hi @chippers! Did you get a chance to look at this yet?

sorry, got a bit distracted with other work. im looking at it now

**Pull request merged**
